### ISSUE TITLE
Add some new feature

### ISSUE THREAD

**Issue by manishanmugavel07** [KowsalyaAarohi10/WhatsApp#4]
Hi Kowsalya,

Please add something 
![Screenshot_2019-07-07-12-01-06-83](https://user-images.githubusercontent.com/54496186/63647990-9bf9fa80-c746-11e9-9432-fe1a19a334f6.png)
new.

**Comment by KowsalyaAarohi10** [comment]
Hi Shanmugam,

i will add and let you know.

**Comment by KowsalyaAarohi10** [comment]
Hi Shanmugam,

Please check. i have added the new feature.
